app/models.py
#
# -*- coding: utf-8 -*-
#
# @Author: Arrack
# @Date:   2020-04-26 21:49:33
# @Last modified by:   Arrack
# @Last Modified time: 2020-04-27 17:54:10
#

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Column
from sqlalchemy import Float
from sqlalchemy import Integer
from sqlalchemy import String


db = SQLAlchemy()


class Movie(db.Model):
    __tablename__ = 'movies'

    id = Column(Integer, primary_key=True)
    rank = Column(Integer, nullable=False)  # 排名
    title = Column(String(64))              # 名称
    type = Column(String(32))               # 类型
    quote = Column(String(128))             # 一句话电影
    ratingNum = Column(Float)               # 评分
    participantsNum = Column(Integer)       # 评论人数
    countryRegion = Column(String(32))      # 国家/地区
    year = Column(String(10))               # 上映年份
    releaseDate = Column(String(128))       # 上映日期
    language = Column(String(64))           # 语言
    director = Column(String(64))           # 导演
    screenwriter = Column(String(128))      # 编剧
    alias = Column(String(256))             # 别名
    stars = Column(String(2048))            # 主演
    duration = Column(String(128))          # 时长
    website = Column(String(128))           # 官方网站
    summary = Column(String(2048))          # 简介
    imdbID = Column(String(16))             # imdb 编号
    imdbUrl = Column(String(128))           # imdb地址
    imgSrc = Column(String(128))            # 图片地址
    awards = Column(String(1024))           # 奖项

    def setAttrs(self, attrs_dict):
        for key, value in attrs_dict.items():
            if hasattr(self, key) and key != 'id':
                setattr(self, key, value)

app/forms.py
#
# -*- coding: utf-8 -*-
#
# @Author: Arrack
# @Date:   2020-04-30 16:56:55
# @Last modified by:   Arrack
# @Last Modified time: 2020-04-30 17:12:32
#

from wtforms import Form, StringField


class SearchForm(Form):
    searchText = StringField()

app/__init__.py
#
# -*- coding: utf-8 -*-
#
# @Author: Arrack
# @Date:   2020-04-26 21:50:25
# @Last modified by:   Arrack
# @Last Modified time: 2020-04-30 18:13:00
#

import click
from flask import Flask

from app.models import db
from app.spider import DoubanSpider
from app.suggestion import sug


def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object('app.config')
    app.config.from_pyfile('secure.py')

    register_blueprint(app)
    register_extensions(app)
    register_command(app)

    return app


def register_blueprint(app):
    from app.views import web
    app.register_blueprint(web)


def register_extensions(app):
    db.init_app(app)
    db.create_all(app=app)
    sug.init_app(app)


def register_command(app):
    @app.cli.command()
    @click.option('--drop', is_flag=True, help='Create after drop.')
    def initdb(drop):
        if drop:
            if click.confirm('This operation will DROP ALL TABLES, continue?'):
                db.drop_all()
                click.echo('All tables have been dropped.')
        db.create_all()
        click.echo('Initialized database.')

    @app.cli.command()
    def crawl():
        click.echo('Begin to crawl douban top 250 movies...')
        spider = DoubanSpider()
        spider.run()
        click.echo('Done.')

app/views.py
#
# -*- coding: utf-8 -*-
#
# @Author: Arrack
# @Date:   2020-04-27 20:51:11
# @Last modified by:   Arrack
# @Last Modified time: 2020-04-30 17:24:20
#

from flask import Blueprint
from flask import current_app
from flask import render_template
from flask import request, jsonify, redirect, url_for

from app.models import Movie
from app.viewModels import IndexMovie
from app.suggestion import sug
from app.forms import SearchForm

web = Blueprint('web', __name__)


@web.route('/top250', methods=['GET', 'POST'])
def top250():
    form = SearchForm(request.form)
    if request.method == 'POST':
        searchText = form.searchText.data
        if searchText:
            return redirect(url_for('web.search', q=searchText))

    page = request.args.get('p')
    page = int(page) if page and page.isdigit() and int(page) else 1
    paginate = Movie.query.order_by(Movie.rank).paginate(page=page, per_page=current_app.config['MOVIES_PER_PAGE'])
    movies = [IndexMovie(m) for m in paginate.items]
    return render_template('index.html', movies=movies, paginate=paginate, form=form)


@web.route('/movies/<int:mid>', methods=['GET', 'POST'])
def movie(mid):
    form = SearchForm(request.form)
    if request.method == 'POST':
        searchText = form.searchText.data
        if searchText:
            return redirect(url_for('web.search', q=searchText))

    movie = Movie.query.get(mid)
    return render_template('movie.html', movie=movie, form=form)


@web.route('/suggestion', methods=['GET'])
def suggestion():
    searchText = request.args.get('q')
    if searchText:
        res = sug.searchPrefix(searchText)
    return jsonify(res)


@web.route('/result', methods=['GET', 'POST'])
def search():
    form = SearchForm(request.form)
    if request.method == 'POST':
        searchText = form.searchText.data
        if searchText:
            return redirect(url_for('web.search', q=searchText))

    searchText = request.args.get('q')
    query = Movie.title.like(searchText + '%')
    movies = Movie.query.order_by(Movie.rank).filter(query).all()
    return render_template('result.html', form=form, movies=movies)

app/templates/base.html
<!DOCTYPE html>
<html class="ua-linux ua-webkit" lang="zh-CN">
 {% block head -%}
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="webkit" name="renderer"/>
  <meta content="always" name="referrer"/>
  <meta content="ok0wCgT20tBBgo9_zat2iAcimtN4Ftf5ccsh092Xeyw" name="google-site-verification"/>
  <title>
   豆瓣电影 Top 250
  </title>
  <meta content="cZdR4xxR7RxmM4zE" name="baidu-site-verification"/>
  <meta content="no-cache" http-equiv="Pragma"/>
  <meta content="Sun, 6 Mar 2005 01:00:00 GMT" http-equiv="Expires"/>
  <link href="https://img3.doubanio.com/f/movie/d59b2715fdea4968a450ee5f6c95c7d7a2030065/pics/movie/apple-touch-icon.png" rel="apple-touch-icon"/>
  <link href="https://img3.doubanio.com/f/shire/3e5dfc68b0f376484c50cf08a58bbca3700911dc/css/douban.css" rel="stylesheet" type="text/css"/>
  <link href="https://img3.doubanio.com/f/shire/ae3f5a3e3085968370b1fc63afcecb22d3284848/css/separation/_all.css" rel="stylesheet" type="text/css"/>
  <link href="https://img3.doubanio.com/f/movie/8864d3756094f5272d3c93e30ee2e324665855b0/css/movie/base/init.css" rel="stylesheet"/>
  <script type="text/javascript">
   var _head_start = new Date();
  </script>
  <script src="https://img3.doubanio.com/f/movie/0495cb173e298c28593766009c7b0a953246c5b5/js/movie/lib/jquery.js" type="text/javascript">
  </script>
  <script src="https://img3.doubanio.com/f/shire/5ecaf46d6954d5a30bc7d99be86ae34031646e00/js/douban.js" type="text/javascript">
  </script>
  <script src="https://img3.doubanio.com/f/shire/0efdc63b77f895eaf85281fb0e44d435c6239a3f/js/separation/_all.js" type="text/javascript">
  </script>
  <link href="https://img3.doubanio.com/f/movie/2c95f768ea74284b900c04c0209b0a44f0a0de52/css/movie/top_movies.css" rel="stylesheet" type="text/css"/>
  <script data-cfg-autoload="false" src="https://img3.doubanio.com/f/shire/77323ae72a612bba8b65f845491513ff3329b1bb/js/do.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   Do.ready(function(){
            $("#mine-selector input[type='checkbox']").click(function(){
                var val = $(this).is(":checked")?$(this).val():"";
                window.location.href = '/top250?filter=' + val;
            })
    })
  </script>
  <style type="text/css">
   img { max-width: 100%; }
  </style>
  <link href="https://img3.doubanio.com/misc/mixed_static/562925b5e3824700.css" rel="stylesheet"/>
  <link href="https://img3.doubanio.com/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
 </head>
 {%- endblock %}
 <body>
  <link href="https://img3.doubanio.com/dae/accounts/resources/1f8d15e/shire/bundle.css" rel="stylesheet" type="text/css"/>
  <script defer="defer" src="//img3.doubanio.com/dae/accounts/resources/1f8d15e/shire/bundle.js">
  </script>
  <link href="https://img3.doubanio.com/dae/accounts/resources/1f8d15e/movie/bundle.css" rel="stylesheet" type="text/css"/>
  <div class="nav" id="db-nav-movie">
   <div class="nav-wrap">
    <div class="nav-primary">
     <div class="nav-logo">
      <a href="{{ url_for('web.top250') }}">
       豆瓣电影
      </a>
     </div>
     <div class="nav-search">
      <form method="post">
        {{ form.csrf_token }}
       <fieldset>
        <legend>
         搜索：
        </legend>
        <label for="query">
        </label>
        <div class="inp" id="inp">
          {{ form.searchText(id="query", placeholder="搜索电影", maxlength="60", size="22") }}
        </div>
        <div class="inp-btn">
         <input type="submit" value="搜索">
        </div>
       </fieldset>
      </form>
      <script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
      <script>
        $(document).ready(function(){
          var css = {
            "margin-left": $("#inp").offset().left,
            "width": $("#query").width() + 13,
            "margin-top": $("#inp").offset().top
          }
          $('#search_suggest').css(css);
          $("#query").keyup(function(){
            if($("#ajaxtest").val() == ""){
              $('#search_suggest').empty();
            }
            var q = $("#query").val();
            $.get("{{ url_for('web.suggestion') }}",{'q': q}, function(data){
              $('#search_suggest').empty();
              for (var i = 0; i < data.length; i++) {
                $('#search_suggest').append("<li style='list-style:none;'><a href='javascript:void(0)'><em>" + data[i][0] + "</em></a></li>")
                $('#search_suggest').show()
                $("#search_suggest li a").mousedown(function () {
                  window.location.href="{{ url_for('web.search') }}?q=" + $(this).text();
                });
              };
            })
          });
          $('#query').blur(function(){
              $('#search_suggest').empty();
              $('#search_suggest').hide();
          })
        });
      </script>
     </div>
    </div>
   </div>
   <div class="nav-secondary">
    <div class="nav-items">
     <ul>
      <li>
       <a href="#">
        影讯&amp;购票
       </a>
      </li>
      <li>
       <a href="#">
        选电影
       </a>
      </li>
      <li>
       <a href="#">
        电视剧
       </a>
      </li>
      <li>
       <a href="#">
        排行榜
       </a>
      </li>
      <li>
       <a href="#">
        分类
       </a>
      </li>
      <li>
       <a href="#">
        影评
       </a>
      </li>
      <li>
       <a href="#">
        2019年度榜单
       </a>
      </li>
      <li>
       <a href="#" target="_blank">
        2019书影音报告
       </a>
      </li>
     </ul>
    </div>
    <a class="movieannual" href="#">
    </a>
   </div>
  </div>
  <script defer="defer" src="//img3.doubanio.com/dae/accounts/resources/1f8d15e/movie/bundle.js">
  </script>
  <div id="wrapper">
   {% block content -%}
   {%- endblock content %}
   <div id="footer">
    <div class="footer-extra">
    </div>
    <span class="fleft gray-link" id="icp">
     © 2005－2020 douban.com, all rights reserved 北京豆网科技有限公司
    </span>
    <a href="https://www.douban.com/hnypt/variformcyst.py" style="display: none;">
    </a>
    <span class="fright">
     <a href="https://www.douban.com/about">
      关于豆瓣
     </a>
     ·
     <a href="https://www.douban.com/jobs">
      在豆瓣工作
     </a>
     ·
     <a href="https://www.douban.com/about?topic=contactus">
      联系我们
     </a>
     ·
     <a href="https://www.douban.com/about/legal">
      法律声明
     </a>
     ·
     <a href="https://help.douban.com/?app=movie" target="_blank">
      帮助中心
     </a>
     ·
     <a href="https://www.douban.com/doubanapp/">
      移动应用
     </a>
     ·
     <a href="https://www.douban.com/partner/">
      豆瓣广告
     </a>
    </span>
   </div>
  </div>
  <!-- COLLECTED JS -->
  <link href="https://img3.doubanio.com/f/shire/8377b9498330a2e6f056d863987cc7a37eb4d486/css/ui/dialog.css" rel="stylesheet" type="text/css"/>
  <link href="https://img3.doubanio.com/f/movie/4aca95d66d37ec0712b3d19973b5d8feb75f2f05/css/movie/mod/reg_login_pop.css" rel="stylesheet" type="text/css"/>
  <script data-cfg-autoload="false" src="https://img3.doubanio.com/f/shire/77323ae72a612bba8b65f845491513ff3329b1bb/js/do.js" type="text/javascript">
  </script>
  <script src="https://img3.doubanio.com/f/shire/383a6e43f2108dc69e3ff2681bc4dc6c72a5ffb0/js/ui/dialog.js" type="text/javascript">
  </script>
  
  <!-- dae-web-movie--default-7f76f67f65-bgv6f-->
  <script>
   _SPLITTEST=''
  </script>
  <div id="search_suggest" style="display: none;"><ul></ul></div>
 </body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content -%}
 <div id="content">
  <h1>
   豆瓣电影 Top 250
  </h1>
  <div class="grid-16-8 clearfix">
   <div class="article">
    <ol class="grid_view">
     {% for movie in movies %}
     <li>
      <div class="item">
       <div class="pic">
        <em class="">
         {{ movie.rank }}
        </em>
        <a href="{{ url_for('web.movie', mid=movie.id) }}">
         <img alt="{{ movie.title }}" src="{{ movie.imgSrc }}" width="100"/>
        </a>
       </div>
       <div class="info">
        <div class="hd">
         <a class="" href="{{ url_for('web.movie', mid=movie.id) }}">
          <span class="title">
           {{ movie.title }}
          </span>
          <span class="other">
           / {{ movie.alias }}
          </span>
         </a>
        </div>
        <div class="bd">
         <p class="">
          {{ movie.director }}
          <br/>
          {{ movie.year }} / {{ movie.countryRegion }} / {{ movie.type }}
         </p>
         <div class="star">
          <span class="rating_num" property="v:average">
           {{ movie.ratingNum }}
          </span>
          <span content="10.0" property="v:best">
          </span>
          <span>
           1{{ movie.participantsNum }}人评价
          </span>
         </div>
         <p class="quote">
          <span class="inq">
           {{ movie.quote }}
          </span>
         </p>
        </div>
       </div>
      </div>
     </li>
     {% endfor %}
    </ol>
    <div class="paginator">
     {% if paginate.has_prev %}
      <a href="{{ url_for('web.top250', p=paginate.prev_num) }}">上一页</a>
     {% endif %}

     {% for page in paginate.iter_pages() %}
      {% if page %}
       <a href="{{ url_for('web.top250', p=page) }}">{{ page }}</a>
      {% else %}
       <a href="#" style="pointer-events: none">&hellip;</a>
      {% endif %}
     {% endfor %}

     {% if paginate.has_next %}
      <a href="{{ url_for('web.top250', p=paginate.next_num) }}">下一页</a>
     {% endif %}
    </div>
   </div>
   <div class="aside">
    <p class="pl">
     豆瓣用户每天都在对“看过”的电影进行“很差”到“力荐”的评价，豆瓣根据每部影片看过的人数以及该影片所得的评价等综合数据，通过算法分析产生豆瓣电影 Top 250。
    </p>
    <!-- douban ad begin -->
    <div class="mobile-app-entrance block5 app-movie">
     <a class="entrance-link" href="https://bixin.com/" target="blank">
      <div class="entrance-qrcode">
       <img alt="扫码下载豆瓣 App" height="80" src="http://www.528btc.com/d/file/2019-04-26/89475b9445ea759d960cd432950e95fb.png" width="80"/>
      </div>
      <div class="entrance-info">
       <span class="main-title">
        币信
       </span>
       <span class="sub-title">
        把区块链装进口袋
       </span>
      </div>
     </a>
    </div>
    <!-- douban ad end -->
   </div>
   <div class="extra">
   </div>
  </div>
 </div>
{%- endblock content %}

app/templates/movie.html
{% extends 'base.html' %}

{% block head -%}
 {{ super() }}
 <link href="https://img3.doubanio.com/misc/mixed_static/36c0e5f6c8538558.css" rel="stylesheet"/>
{%- endblock %}

{% block content -%}
 <div id="content">
  <!-- top 250 begin -->
  <div class="top250">
   <span class="top250-no">
    No.{{ movie.rank }}
   </span>
   <span class="top250-link">
    <a href="https://movie.douban.com/top250" target="_blank">
     豆瓣电影Top250
    </a>
   </span>
  </div>
  <!-- top 250 end -->
  <div id="dale_movie_subject_top_icon">
  </div>
  <h1>
   <span property="v:itemreviewed">
    {{ movie.title }}
   </span>
   <span class="year">
    ({{ movie.year }})
   </span>
  </h1>
  <div class="grid-16-8 clearfix">
   <div class="article">
    <div class="indent clearfix">
     <div class="subjectwrap clearfix">
      <div class="subject clearfix">
       <div class="" id="mainpic">
        <img alt="The Shawshank Redemption" rel="v:image" src="{{ movie.imgSrc }}" title="点击看更多海报"/>
       </div>
       <div id="info">
        <span>
         <span class="pl">
          导演
         </span>
         :
         <span class="attrs">
          {{ movie.director }}
         </span>
        </span>
        <br/>
        <span>
         <span class="pl">
          编剧
         </span>
         :
         <span class="attrs">
          {{ movie.screenwriter }}
         </span>
        </span>
        <br/>
        <span class="actor">
         <span class="pl">
          主演
         </span>
         :
         <span class="attrs" style="display: -webkit-box;overflow: hidden;text-overflow: ellipsis;-webkit-line-clamp: 2;-webkit-box-orient: vertical;">
          {{ movie.stars }}
         </span>
        </span>
        <span class="pl">
         类型:
        </span>
        {{ movie.type }}
        <br/>
        <span class="pl">
         制片国家/地区:
        </span>
        {{ movie.countryRegion }}
        <br/>
        <span class="pl">
         语言:
        </span>
        {{ movie.language }}
        <br/>
        <span class="pl">
         上映日期:
        </span>
        {{ movie.releaseDate }}
        <br/>
        <span class="pl">
         片长:
        </span>
        {{ movie.duration }}
        <br/>
        <span class="pl">
         又名:
        </span>
        {{ movie.alias }}
        <br/>
        <span class="pl">
         IMDb链接:
        </span>
        <a href="{{ movie.imdbUrl }}" rel="nofollow" target="_blank">
         {{ movie.imdbID }}
        </a>
        <br/>
       </div>
      </div>
      <div id="interest_sectl">
       <div class="rating_wrap clearbox" rel="v:rating">
        <div class="clearfix">
         <div class="rating_logo ll">
          豆瓣评分
         </div>
         <div class="output-btn-wrap rr" style="display:none">
          <img src="https://img3.doubanio.com/f/movie/692e86756648f29457847c5cc5e161d6f6b8aaac/pics/movie/reference.png"/>
          <a class="download-output-image" href="#">
           引用
          </a>
         </div>
        </div>
        <div class="rating_self clearfix" typeof="v:Rating">
         <strong class="ll rating_num" property="v:average">
          {{ movie.ratingNum }}
         </strong>
         <div class="rating_right">
          <div class="ll bigstar bigstar50">
          </div>
          <div class="rating_sum">
           <span property="v:votes">
            {{ movie.participantsNum }}
           </span>
           人评价
          </div>
         </div>
        </div>
       </div>
      </div>
     </div>
    </div>
    <div class="related-info" style="margin-bottom:-10px;">
     <a name="intro">
     </a>
     <h2>
      <i class="">
       {{ movie.title }}的剧情简介
      </i>
      · · · · · ·
     </h2>
     <div class="indent" id="link-report">
      <span>
       {{ movie.summary }}
      </span>
     </div>
    </div>
   </div>
  </div>
 </div>
{%- endblock %}

app/templates/result.html
{% extends 'base.html' %}

{% block content -%}
 <div id="content">
  <h1>
   搜索结果
  </h1>
  <div class="grid-16-8 clearfix">
   <div class="article">
    {% if movies %}
    <ol class="grid_view">
     {% for movie in movies %}
     <li>
      <div class="item">
       <div class="pic">
        <em class="">
         {{ movie.rank }}
        </em>
        <a href="{{ url_for('web.movie', mid=movie.id) }}">
         <img alt="{{ movie.title }}" src="{{ movie.imgSrc }}" width="100"/>
        </a>
       </div>
       <div class="info">
        <div class="hd">
         <a class="" href="{{ url_for('web.movie', mid=movie.id) }}">
          <span class="title">
           {{ movie.title }}
          </span>
          <span class="other">
           / {{ movie.alias }}
          </span>
         </a>
        </div>
        <div class="bd">
         <p class="">
          {{ movie.director }}
          <br/>
          {{ movie.year }} / {{ movie.countryRegion }} / {{ movie.type }}
         </p>
         <div class="star">
          <span class="rating_num" property="v:average">
           {{ movie.ratingNum }}
          </span>
          <span content="10.0" property="v:best">
          </span>
          <span>
           1{{ movie.participantsNum }}人评价
          </span>
         </div>
         <p class="quote">
          <span class="inq">
           {{ movie.quote }}
          </span>
         </p>
        </div>
       </div>
      </div>
     </li>
     {% endfor %}
    </ol>
    {% else %}
    <p class="pl">抱歉，没找着</p>
    {% endif %}
   </div>
   <div class="aside">
    <p class="pl">
     豆瓣用户每天都在对“看过”的电影进行“很差”到“力荐”的评价，豆瓣根据每部影片看过的人数以及该影片所得的评价等综合数据，通过算法分析产生豆瓣电影 Top 250。
    </p>
    <!-- douban ad begin -->
    <div class="mobile-app-entrance block5 app-movie">
     <a class="entrance-link" href="https://bixin.com/" target="blank">
      <div class="entrance-qrcode">
       <img alt="扫码下载豆瓣 App" height="80" src="http://www.528btc.com/d/file/2019-04-26/89475b9445ea759d960cd432950e95fb.png" width="80"/>
      </div>
      <div class="entrance-info">
       <span class="main-title">
        币信
       </span>
       <span class="sub-title">
        把区块链装进口袋
       </span>
      </div>
     </a>
    </div>
    <!-- douban ad end -->
   </div>
   <div class="extra">
   </div>
  </div>
 </div>
{%- endblock content %}